model :
  DCUNET : 
    # num_frame must be multiple of 16
    num_frame : 160
    # input : 'noisy', 'estim'
    input : 'noisy'
    post_filter: false
    version : 2
---
train:
  epoch: 200
  # 12
  batch_size: 12
  # 16
  num_workers: 16
  optimizer: 'adam'
  adam: 0.0001
  adabound:
    initial: 0.001
    final: 0.05
  frame_num: 1024

  summary_interval: 10
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'wSDR'
---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio:
  frame : 1024
  shift : 256
  samplerate : 16000
---
data:
  root: '/home/data/kbh/3-channel-dnn/'
---
  log:
    root: '/home/nas/user/kbh/3-channel-dnn/'
